theme = "darcula-solid"

[editor]
auto-pairs = false # defaults to `true`
bufferline = "multiple" # shows multiple buffers as tab bar

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal]
";" = { w = ":w" }

[keys.normal.' ']
# Toggle rendering whitespace
w = ":toggle whitespace.render all none"

# Clear trailing whitespace, yoinked off the internet
S-s = [
    "save_selection",
    "select_all",
    # Delete trailing whitespace from end of each line
    ":pipe sed 's/[ \t]*$//'",
    # Delete trailing blank lines (including whitespace) from end of the buffer
    ":pipe awk '/^\\s*$/ {b=b $0 \"\\n\"; next;} {printf \"%s\",b; b=\"\"; print;}'",
    "collapse_selection",
    "jump_backward",
    "commit_undo_checkpoint",
    ":write",
]
